# http://about.travis-ci.org/docs/user/ci-environment/
# http://about.travis-ci.org/docs/user/build-configuration/
# Travis uses Ubuntu 64 12.04
branches:
    only:
        - master

language: python
python:
    - "2.7" 
compiler:
    - gcc

before_install:
    - sudo apt-get install -y build-essential libpng12-dev libfreetype6-dev python-dev libopenblas-dev libopenblas-base liblapack-dev gfortran  git python python-pip libsqlite3-dev wget
#    - liblapack3 
    # ATLAS matrix library 
    - sudo apt-get install -y build-essential libatlas-base-dev python-dev python-yaml git portaudio19-dev libsox-dev
    - pip install -r alex-requirements.txt
    - easy_install pysox
    - pip install pystache cython flask theano
    - pip install --allow-unverified pyaudio --allow-unverified pyaudio pyaudio
    - pip install pyfst
    - mkdir tmp/
    - cd tmp/
    - git clone https://github.com/UFAL-DSG/pjsip.git
    - cd pjsip
    - ./configure CXXFLAGS=-fPIC CFLAGS=-fPIC LDFLAGS=-fPIC CPPFLAGS=-fPIC
    - make dep
    - make
    - make install
    - cd pjsip-apps/src/python/
    - python setup-pjsuaxt.py install

#install: 
#    - pip install -q cython pystache pyyaml --use-mirrors
#    - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]] ; then pip install --use-mirrors unittest2 ordereddict argparse ; fi
#    # Openfst: building
#    - pushd tools && make -j 4 openfst_tgt && popd
#    # hack how to make available clapack.h
#    - pushd tools && make -j 4 atlas && popd
#    # Configure with ATLAS (default)
#    - pushd src && ./configure --shared && popd
#    - pushd src && make -j 4 && popd
#    - pushd src/onl-rec && make -j 4 && popd

script:
    - echo "ahoj"
